name: CI

on:
  push:
    branches: [main, "codex/*"]
  pull_request:
    branches: [main, "codex/*"]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest

      - name: Install dependencies
        run: bun install --frozen-lockfile

      - name: Lint
        run: bun run lint || bun x eslint . --max-warnings 0

      - name: Type check (compile-only)
        run: |
          echo "🧠 Running type-level tests..."
          bun x tsc --noEmit --skipLibCheck --project tsconfig.json

      - name: Run tests
        run: |
          echo "🧪 Running bun test..."
          bun test --coverage
